EIGEN_PATH = '/usr/include/eigen3';
SRC = '../cpp/src';
INC = '../cpp/include';

disp('Running >> mex mexGPisMap2.cpp covFnc.cpp ObsGP.cpp OnGPIS.cpp strct.cpp quadtree.cpp octree.cpp GPisMap2.cpp...');
mex('mexGPisMap2.cpp',...
    strcat(SRC,'/covFnc.cpp'),...
    strcat(SRC,'/ObsGP.cpp'),...
    strcat(SRC,'/OnGPIS.cpp'),...
    strcat(SRC,'/strct.cpp'),...
    strcat(SRC,'/octree.cpp'),...
    strcat(SRC,'/GPisMap2.cpp'),...
    strcat('-I', INC),...
    strcat('-I', EIGEN_PATH),...
    'CXXFLAGS=-std=c++11 -pthread -fPIC','-O');
