EIGEN_PATH = '/usr/include/eigen3';
SRC = '../cpp/src';
INC = '../cpp/include';

disp('Running >> mex mexGPShape.cpp covFnc.cpp ObsGP.cpp OnGPIS.cpp strct.cpp quadtree.cpp octree.cpp GPShape.cpp...');
mex('mexGPShape.cpp',...
    strcat(SRC,'/covFnc.cpp'),...
    strcat(SRC,'/ObsGP.cpp'),...
    strcat(SRC,'/OnGPIS.cpp'),...
    strcat(SRC,'/strct.cpp'),...
    strcat(SRC,'/quadtree.cpp'),...
    strcat(SRC,'/GPShape.cpp'),...
    strcat('-I',INC),...
    strcat('-I', EIGEN_PATH),...
    'CXXFLAGS=-std=c++11 -pthread -fPIC','-O');
